### ISSUE TITLE
Dangerous try/catch blocks in fireCallbacks

### ISSUE THREAD

**Issue by pmowrer** [CC-Archived/promise-as3#10]
The try/catch blocks in `Callbacks.as`'s `fireCallbacks` method seem unnecessary and are somewhat dangerous since they wrap execution of the callback. Any error in the call stack that results from the callback will be much harder to track down as a result. I think they should just be removed.

**Comment by johnyanarella** [comment]
This issue refers to the now-abandoned jQuery 1.4-style implementation.

promise-as3 has been rewritten to implement the [Promises/A+ specification](https://github.com/promises-aplus/promises-spec).
