### ISSUE TITLE
Support Promise/A then() functionality w/chaining

### ISSUE THREAD

**Issue by johnyanarella** [CC-Archived/promise-as3#2]
Add support for Promise/A then() functionality, as in our current pipe() method.

**Comment by darscan** [comment]
Close the issue?

**Comment by johnyanarella** [comment]
Nope. :)

The current when() and then() functionality matches jQuery's implementation, rather than Promise/A.  This has yet to be resolved.  We may yet still maintain a facade that implements the jQuery syntax and behavior.

Thomas's commit above was just a minor step in that direction.

**Comment by darscan** [comment]
I see. Serves me right for not actually looking through the code :)

**Comment by johnyanarella** [comment]
Rewritten to conform to the [Promises/A+ specification](https://github.com/promises-aplus/promises-spec).

The original jQuery style implementation has moved to the Abandoned branch.
