### ISSUE TITLE
Zip implementation

### ISSUE THREAD

**Issue by ryandbair** [CC-Archived/promise-as3#21]
I came across a case where I need to combine multiple Promises into one, similar to other Promise implementation's zip feature (such as Scala's). 

I put together a solution which can be used like so:

```
promise1.zip(promise2,promise3).then(
function(a:Array):int { /* do stuff with results */ }
);
```

I didn't see anything like this in the Promises/A+ specs, but I think it would be useful to many people. If its something you would like to include, I can clean up the code and submit a pull request. 

Interested?

**Comment by johnyanarella** [comment]
I just added a `Promise.all()` utility function which addresses this need similarly to how the various JavaScript Promises/A+ implementations have.

``` ActionScript
Promise
  .all( [ promise1, promise2, promise3 ] )
  .then( function ( fulfilledValues:Array ):int {
    // do stuff with results
  } );
```

**NOTE:** The parameter passed to `Promise.all()` can be an Array of values and/or Promises, or even _a Promise of_ an Array of values and/or Promises.

You might also be interested in the new `spread` utility function, too:

``` ActionScript
import com.codecatalyst.util.spread;

// ...

Promise
  .all( [ promise1, promise2, promise3 ] )
  .then( spread( function( value1:int, value2:int, value3:int ):int {
    // do stuff with results
  } ) );
```
