### ISSUE TITLE
Promise.timeout should throw a Typed Error

### ISSUE THREAD

**Issue by petermd** [CC-Archived/promise-as3#39]
Promise.timeout throws an Error("message") when timeout occurs. Knowing the difference between a failure and a timeout can be useful.

Suggest adding a TimeoutError instead (similar to CancellationError) so a generic handler can discriminate.

Will create a pull-request unless there is an alternative i've missed?

**Comment by honzabrecka** [comment]
+1

**Comment by k7sleeper** [comment]
Just created a PR  #41 for that enhancement.

**Comment by petermd** [comment]
Great. Thx.
