### ISSUE TITLE
Promise Chaining

### ISSUE THREAD

**Issue by reyco1** [CC-Archived/promise-as3#53]
Can someone demonstrate a quick example on how to chain n promises? I tried to use Promise.when() but am having a hard time grasping the concept. Thanks!

**Comment by honzabrecka** [comment]
Just use:

``` as3
fnReturingPromiseA().then(function(result:whatever):void {
  return fnReturingPromiseB(result);
}).then(function(result:whatever):void {
  return fnReturingPromiseC(result);
})
```

or:

``` as3
fnReturingPromiseA()
   .then(fnReturingPromiseB)
   .then(fnReturingPromiseC)
```

**Comment by reyco1** [comment]
The problem is that it could be any number of promises and I don't know that number at compile time. Basically, I have an app that can upload multiple images to a firebase database. The number of images chosen is dictated by the user, hence I can't apply the ".then" manually. I tried adding it in a loop but that does not seem to work either.

**Comment by reyco1** [comment]
Here is a snippet of that code:

`for (var i:int = 0; i < data.length; i++)
            {
                var image:Object = data[i];
                var imageData:Object = {
                    imageName: firebase.userData.localId + "/" + new Date().getTime() + ".jpg",
                    bytes: BitmapdataUtil.toByteArray(image.bitmapData, image.orientation ? image.orientation : null)
                };

                if (i == 0)
                {
                    promise = new UploadListingImageCommand(imageData).execute();
                }
                else
                {
                    promise.then(function (result:Object):Promise
                    {
                        return new UploadListingImageCommand(imageData).execute();
                    })
                }
            }`

**Comment by reyco1** [comment]
Figured it out... This returns the desired result:

```
var arr:Array = ["A", "B", "C", "D", "E"];
var s:AsynchPromise = new AsynchPromise("A");
var promise:Promise = s.execute();

for (var i:int = 1; i < arr.length; i++)
{
   var id:String = arr[i];
   var newAsynch:AsynchPromise = new AsynchPromise(id);
   promise = Promise.when(promise).then(newAsynch.execute);
}
```

it works the same way as doing this:

```
var s:AsynchPromise = new AsynchPromise("A");
s.execute()
.then(new AsynchPromise("B").execute)
.then(new AsynchPromise("C").execute)
.then(new AsynchPromise("D").execute)
.then(new AsynchPromise("E").execute)
```
