### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by darscan** [CC-Archived/promise-as3#6]
This project was a little hard to find for some reason. Just wondering if a name like as3-deferred might not be easier to find - especially for people looking for an as3 implementation of jQuery's Deferred.

**Comment by johnyanarella** [comment]
Yeah, that's the issue right there. :)

Despite Thomas's README commit, the intention is not to clone jQuery's implementation (aka Deferred), but rather to create an ActionScript / Flex flavored implementation of Promises.

jQuery's Deferred is just a fairly recent implementation of Promises.  The history goes back quite a ways, across a number of languages.  jQuery's implementation takes some interesting liberties.

We're intentionally under the radar right now.  Once the API solidifies, I plan to promote the library, which should hopefully help with that issue.  I commissioned a logo from a designer friend of mine which will be used as part of that push.

Unfortunately, my paying work these days has been native mobile and HTML/CSS/JavaScript, so my efforts on this project have been stalled for a bit.  I'm eager to get back to this in the next couple weeks and get it 'out the door' and in use.

**Comment by darscan** [comment]
Yep, I'm aware of the history behind this kind of thing - Q, CJS Promise/A, K, Futures, etc :)

Not to be difficult, but I'm not sure I understand why you're wanting to keep this under the radar? Surely tagging it as v0.0.1 (or indeed, leaving it untagged) is enough to let people know that it hasn't been released?

Nevertheless, great work. I look forward to playing around when the API solidifies. More specifically, I look forward to obliterating the hideous Promise implementation I wrote a while back and switching to this when it's ready :)
