### ISSUE TITLE
Promise.when handlers expects exactly one argument

### ISSUE THREAD

**Issue by pmowrer** [CC-Archived/promise-as3#8]
This issue is filed under the assumption that a promise may resolve/reject/notify/cancel with any number of arguments (or none).

The following will cause an argument count mismatch error to be thrown:

``` as3
var dfd:Deferred = new Deferred();
Promise.when(dfd.promise);
dfd.resolve();
```

Easy fix is to modify the inline handlers in `.when` to take rest parameters. Question is what the expectations should be for the arguments. For example, in `testWhen_withFunction`, a `null` argument is expected when a function is passed -- now that'll be an `array` containing a `null`.

**Comment by johnyanarella** [comment]
This issue refers to the now-abandoned jQuery 1.4-style implementation.

promise-as3 has been rewritten to implement the [Promises/A+ specification](https://github.com/promises-aplus/promises-spec).
